p=int(input("enter the initial principal:"))
r=int(input("enter the rate percentage: "))
t=int(input("enter the time period:"))
n=int(input("enter the no of times to calculate interest:"))
a=p*((1+r/n) ** (n*t))
print(a)